version: '2'
networks: 
  test:
volumes: 
  devpeer:
  devpeer-worldstate:
  orderer:
  data-ca:

services: 
  devpeer:
    container_name: devpeer
    extends: 
      file: base/base.yaml
      service: peer-base
    environment: 
      - CORE_PEER_ID=devpeer
      - CORE_PEER_ADDRESS=devpeer:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=devpeer:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=devpeer:7051
      - CORE_PEER_LOCALMSPID=DevMSP

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=database:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    volumes: 
        - /var/run/:/host/var/run/
        - ../Blockchain/test-network/crypto-config/peerOrganizations/devorg/peers/devpeer/msp:/etc/hyperledger/fabric/msp
        - devpeer:/var/hyperledger/production
    networks: 
      - test
    ports: 
      - 7051:7051
  
  orderer:
    extends:
      file:   ./base/base.yaml
      service: orderer-base
    container_name: orderer
    volumes:
        - ../Blockchain/test-network/channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../Blockchain/test-network/crypto-config/ordererOrganizations/orderer/orderers/orderer/msp:/var/hyperledger/orderer/msp
        - orderer:/var/hyperledger/production/orderer
    networks: 
       - test
    ports: 
      - 7050:7050


  database:
        container_name: database
        image: hyperledger/fabric-couchdb
        environment:
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=adminpw
        volumes:
            - devpeer-worldstate:/opt/couchdb
        networks:
            - test
        ports: 
          - 5984:5984
        depends_on:
          - devpeer

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:2.0
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=devpeer:7051
      - CORE_PEER_LOCALMSPID=DevMSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/devorg/users/Admin@devorg/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ../Blockchain/Chaincode/:/opt/gopath/src/chaincode
        - ../Blockchain/test-network/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto
        - ../Blockchain/test-network/channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    networks:
      - test
  
  ca:
        container_name: ca
        extends:
            file: ./base/base.yaml
            service: ca-base
        environment:
            - FABRIC_CA_SERVER_CA_NAME=ca
        volumes:
            - ../Blockchain/test-network/crypto-config/peerOrganizations/devorg/ca:/ca
            - data-ca:/etc/hyperledger/fabric-ca-server
        ports:
            - 7054:7054
        networks:
            - test
            
  # bcnodeapi:
  #   container_name: bcnodeapi
  #   image: zzocker20/fabricnodeapi
    # networks: 
    #   - test
    # ports: 
    #   - 3000:3000